name: Build Check

on:
  push:
    branches:
      - main
      - feature/*
      - enhancement/*
      - bugfix/*
      - hotfix/*
      - release/*
      - test/*
      - refactor/*
      - ci/*
      - style/*
      - docs/*
      - chore/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
